---
- name: Update system packages
  package:
    name: "*"
    state: latest

- name: Install base packages
  package:
    name:
      - git
      - curl
      - wget
      - htop
      - stow
      - fish-shell
      - xsetroot
      - xset
      - dex
      - redshift
      - lxsession
      - xrdb
      - xinput
      - setxkbmap
    state: present

- name: Clone dotfiles
  become: false
  git:
    repo: "{{ dotfiles_repo }}"
    dest: "{{ dotfiles_dir }}"
    version: main
    update: yes

- name: Apply dotfiles with stow
  become: false
  command: stow --adopt --override='.*' .
  args:
    chdir: "{{ dotfiles_dir }}"

- name: Create user directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0755
  loop:
    - "/home/{{ username }}/code"
    - "/home/{{ username }}/docs"
    - "/home/{{ username }}/dl"
    - "/home/{{ username }}/media"
