---
- name: Allowing user to turn off or reboot the machine
  ansible.builtin.copy:
    dest: "/etc/sudoers.d/shutdown"
    content: |
      {{ username }} ALL=(ALL) NOPASSWD: /usr/bin/poweroff
      {{ username }} ALL=(ALL) NOPASSWD: /usr/bin/reboot
    owner: root
    group: root
    mode: '0440'
    validate: '/usr/sbin/visudo -cf %s'
    
- name: Enable Bluetooth service (runit)
  become: true
  file:
    src: /etc/sv/bluetoothd
    dest: /var/service/bluetoothd
    state: link

- name: Add user to bluetooth group
  user:
    name: "alves"
    groups: bluetooth
    append: yes
