---
- name: Install Bluetooth stack
  package:
    name:
      - bluez
      - bluez-alsa
      - pulseaudio-bluetooth
    state: present

- name: Enable Bluetooth service (runit)
  file:
    src: /etc/sv/bluetoothd
    dest: /var/service/bluetoothd
    state: link

- name: Add user to bluetooth group
  user:
    name: "{{ username }}"
    groups: bluetooth
    append: yes
