---
- name: Install Docker
  package:
    name: docker
    state: present

- name: Enable Docker service (runit)
  file:
    src: /etc/sv/docker
    dest: /var/service/docker
    state: link

- name: Add user to docker group
  user:
    name: "{{ username }}"
    groups: docker
    append: yes
